<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sayed-Sadat" failures="2" tests="4" name="Test" time="10.063" errors="0" timestamp="2023-09-14T23:18:59 PDT">
  <testcase classname="tests.LoginTest" name="assertionFalse" time="0.021">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at tests.LoginTest.assertionFalse(LoginTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- assertionFalse -->
  <testcase classname="tests.LoginTest" name="assertionTrue" time="0.006"/>
  <testcase classname="tests.LoginTest" name="exceptionFail" time="0.005">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at tests.LoginTest.exceptionFail(LoginTest.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- exceptionFail -->
  <testcase classname="tests.LoginTest" name="loginTestPage" time="1.08"/>
</testsuite> <!-- Test -->
